/*
CREATE DATABASE IF NOT EXISTS db_agenda;
USE db_agenda;
CREATE TABLE IF NOT EXISTS contato
(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255),
    fone VARCHAR(255),
    email VARCHAR(255)
);
*/
