# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Projeto 07 - ScrollView TouchesBegan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Projeto 07 - ScrollView TouchesBegan
  pod 'IQKeyboardManager' 

end
